MultiServer:
  enabled: false
  network_latency_milliseconds: 500
  disable_rewards_here: false
#
AutoSave:
  everyMinutes: 2
#
Leaderboard:
  refreshMinutes: 1
AntiAFK:
  afkAfterSeconds: 10
Database:
  type: H2
  name: ultra_playtime
  table_userdata: user_data
  table_no_leaderboard: users_not_leaderboard
  host: "localhost"
  port: "3306"
  user: "root"
  password: "yourPassword"
  connectionTimeout: 160000
  idleTimeout: 600000
  maxLifeTime: 1800000
  maxPoolSize: 10
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    verifyServerCertificate: false
    useSSL: false
    requireSSL: false
    allowPublicKeyRetrieval: false
  